// Regression test for the DER walk that reads Apple's nonce extension.
//
// WHY THIS EXISTS. The OID pattern was hand-typed with the wrong length byte,
// so it matched no certificate on earth and every attestation failed with
// "nonce extension not found". It failed closed, which is the correct direction
// to fail, but it was invisible: one wrong digit in a row of hex.
//
// This drives the real parser against a real X.509 certificate that genuinely
// carries the extension, generated by openssl rather than by the same code
// being tested.
//
//   node --test test/attest-der.test.mjs
//
// The fixture is generated by test/make-fixture.sh and committed, so the test
// does not need openssl to run.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { X509Certificate, createHash } from 'node:crypto';
import {
  encodeOID, extensionValue, parseAuthenticatorData, NONCE_OID_BYTES
} from '../api/_attest.js';
import { decodeCBOR } from '../api/_cbor.js';

const NONCE = Buffer.alloc(32, 0xab);

test('the nonce OID encodes to exactly what Apple puts in the certificate', () => {
  const der = encodeOID('1.2.840.113635.100.8.2');
  // Nine content bytes, not ten. This is the bug that broke Stage B.
  assert.equal(der[1], 9);
  assert.equal(der.toString('hex'), '06092a864886f763640802');
});

test('and the constant the VERIFIER uses is that same encoding', () => {
  // THE TEST THAT WOULD ACTUALLY HAVE CAUGHT IT. The first version of this
  // file checked `encodeOID` and `extensionValue` separately and passed
  // happily with the broken constant still in place, because nothing asserted
  // what verifyAttestation itself reaches for. A regression test that does not
  // catch the regression is worse than no test, because it is believed.
  assert.deepEqual(NONCE_OID_BYTES, encodeOID('1.2.840.113635.100.8.2'));
  assert.equal(NONCE_OID_BYTES[1], 9);
});

test('a few known OIDs encode correctly, so the encoder itself is trustworthy', () => {
  assert.equal(encodeOID('1.2.840.113549.1.1.11').toString('hex'),
               '06092a864886f70d01010b');           // sha256WithRSA
  assert.equal(encodeOID('1.2.840.10045.2.1').toString('hex'),
               '06072a8648ce3d0201');               // id-ecPublicKey
  assert.equal(encodeOID('2.5.29.17').toString('hex'),
               '0603551d11');                       // subjectAltName
});

test('the nonce is extracted from a real certificate carrying the extension', () => {
  const pem = readFileSync(new URL('./fixture-nonce-cert.pem', import.meta.url), 'utf8');
  const cert = new X509Certificate(pem);
  // Driven with the PRODUCTION constant, not a freshly computed one.
  const value = extensionValue(cert.raw, NONCE_OID_BYTES);
  // Apple wraps it as SEQUENCE { [1] { OCTET STRING nonce } }, so the digest is
  // the trailing 32 bytes, which is what verifyAttestation compares.
  assert.deepEqual(value.subarray(value.length - 32), NONCE);
});

test('a certificate without the extension fails closed rather than guessing', () => {
  const pem = readFileSync(new URL('./fixture-plain-cert.pem', import.meta.url), 'utf8');
  const cert = new X509Certificate(pem);
  assert.throws(
    () => extensionValue(cert.raw, NONCE_OID_BYTES),
    /nonce extension not found/);
});

test('the nonce comparison is still SHA256(authData || SHA256(clientData))', () => {
  // Not a change, a guard: the fix touched only how the OID is encoded, and
  // this asserts the derivation around it is untouched.
  const authData = Buffer.alloc(37, 3);
  const challenge = Buffer.from('a challenge');
  const clientDataHash = createHash('sha256').update(challenge).digest();
  const expected = createHash('sha256')
    .update(Buffer.concat([authData, clientDataHash])).digest();
  assert.equal(expected.length, 32);
  // Changing either input changes the nonce, which is the whole point of it.
  const other = createHash('sha256')
    .update(Buffer.concat([Buffer.alloc(37, 4), clientDataHash])).digest();
  assert.notDeepEqual(expected, other);
});

test('authenticator data is still read by fixed offset and rejects short input', () => {
  const auth = Buffer.concat([
    Buffer.alloc(32, 7), Buffer.from([0x40]), Buffer.from([0, 0, 0, 5]),
    Buffer.from('appattestdevelop'), Buffer.from([0, 4]), Buffer.from([1, 2, 3, 4])
  ]);
  const parsed = parseAuthenticatorData(auth);
  assert.equal(parsed.counter, 5);
  assert.equal(parsed.aaguid.toString(), 'appattestdevelop');
  assert.throws(() => parseAuthenticatorData(Buffer.alloc(10)), /too short/);
});

test('the CBOR decoder stays strict', () => {
  assert.throws(() => decodeCBOR(Buffer.from('a26161016162420102ff', 'hex')), /trailing/);
  assert.throws(() => decodeCBOR(Buffer.from('c0', 'hex')), /unsupported major type/);
});
